package com.cnh.GeneratorDao;

import com.cnh.dataobject.MiaoShaOrder;

public interface MiaoShaOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    int insert(MiaoShaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    int insertSelective(MiaoShaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    MiaoShaOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    int updateByPrimaryKeySelective(MiaoShaOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miaosha_order
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    int updateByPrimaryKey(MiaoShaOrder record);
}