package com.cnh.dataobject;

public class Favorite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.id
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.phone_id
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    private Integer phoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.user_id
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.status
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.id
     *
     * @return the value of favorite.id
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.id
     *
     * @param id the value for favorite.id
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.phone_id
     *
     * @return the value of favorite.phone_id
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    public Integer getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.phone_id
     *
     * @param phoneId the value for favorite.phone_id
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    public void setPhoneId(Integer phoneId) {
        this.phoneId = phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.user_id
     *
     * @return the value of favorite.user_id
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.user_id
     *
     * @param userId the value for favorite.user_id
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.status
     *
     * @return the value of favorite.status
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.status
     *
     * @param status the value for favorite.status
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}