package com.cnh.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class MiaoShaGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.id
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.goods_id
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.miaosha_price
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    private BigDecimal miaoshaPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.miaosha_stock
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    private Integer miaoshaStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.start_date
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miaosha_goods.end_time
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.id
     *
     * @return the value of miaosha_goods.id
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.id
     *
     * @param id the value for miaosha_goods.id
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.goods_id
     *
     * @return the value of miaosha_goods.goods_id
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.goods_id
     *
     * @param goodsId the value for miaosha_goods.goods_id
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.miaosha_price
     *
     * @return the value of miaosha_goods.miaosha_price
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public BigDecimal getMiaoshaPrice() {
        return miaoshaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.miaosha_price
     *
     * @param miaoshaPrice the value for miaosha_goods.miaosha_price
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public void setMiaoshaPrice(BigDecimal miaoshaPrice) {
        this.miaoshaPrice = miaoshaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.miaosha_stock
     *
     * @return the value of miaosha_goods.miaosha_stock
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public Integer getMiaoshaStock() {
        return miaoshaStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.miaosha_stock
     *
     * @param miaoshaStock the value for miaosha_goods.miaosha_stock
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public void setMiaoshaStock(Integer miaoshaStock) {
        this.miaoshaStock = miaoshaStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.start_date
     *
     * @return the value of miaosha_goods.start_date
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.start_date
     *
     * @param startDate the value for miaosha_goods.start_date
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miaosha_goods.end_time
     *
     * @return the value of miaosha_goods.end_time
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miaosha_goods.end_time
     *
     * @param endTime the value for miaosha_goods.end_time
     *
     * @mbggenerated Sat Aug 03 09:01:16 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}