package com.cnh.dataobject;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.phone_id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private int phoneId;



    private int releaseId;

    public Integer getReleaseId() {
        return releaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param releaseId the value for order.id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setReleaseId(Integer releaseId) {
        this.releaseId = releaseId;
    }

    private Date date;

    public Date getDate() {
        return date;
    }


    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private int userId;


    private String comment;
    public String getComment(){return comment; }
    public void setComment(String comment){this.comment=comment;}


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.phone_id
     *
     * @return the value of order.phone_id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public int getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.phone_id
     *
     * @param phoneId the value for order.phone_id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setPhoneId(int phoneId) {
        this.phoneId = phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public int  getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}