package com.cnh.dataobject;

public class Phone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.name
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private String phoneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.img_url
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.price
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.status
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.store
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private String store;
    private String cont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.type
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    private String types;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.id
     *
     * @return the value of phone.id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.id
     *
     * @param id the value for phone.id
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.name
     *
     * @return the value of phone.name
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public String getPhoneName() {
        return phoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.name
     *
     * @param phoneName the value for phone.name
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setPhoneName(String phoneName) {
        this.phoneName = phoneName == null ? null : phoneName.trim();
    }



    public String getCont() {
        return cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.name
     *
     * @param cont the value for phone.name
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setCont(String cont) {
        this.cont = cont == null ? null : cont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.img_url
     *
     * @return the value of phone.img_url
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.img_url
     *
     * @param imgUrl the value for phone.img_url
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.price
     *
     * @return the value of phone.price
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.price
     *
     * @param price the value for phone.price
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.status
     *
     * @return the value of phone.status
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.status
     *
     * @param status the value for phone.status
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.store
     *
     * @return the value of phone.store
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public String getStore() {
        return store;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.store
     *
     * @param store the value for phone.store
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setStore(String store) {
        this.store = store == null ? null : store.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.type
     *
     * @return the value of phone.type
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.type
     *
     * @param types the value for phone.type
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }
}