package com.cnh.dao;

import com.cnh.dataobject.Favorite;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    int insert(Favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    int insertSelective(Favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    Favorite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    int updateByPrimaryKeySelective(Favorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbggenerated Fri Apr 17 00:44:15 CST 2020
     */
    int updateByPrimaryKey(Favorite record);


    List<Favorite> findAll(int userId);

    Favorite findVByuserIdAndPhoneId(@Param("userId") int userId, @Param("phoneId") int phoneId);
}