package com.cnh.dao;

import com.cnh.dataobject.OrderUserPhone;
import com.cnh.dataobject.Orders;
import com.cnh.dataobject.Orders;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.stereotype.Repository;

import java.util.List;


@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    int insert(Orders record);


    void delete(int id);


    OrderUserPhone findById(int id);
    List<Orders> findByPhoneId(int phoneId);

    List<OrderUserPhone> findAll();
   List<OrderUserPhone> findAllByStatus(int status);

    List<OrderUserPhone>  findByUserIdPhone(int userId);


    List<OrderUserPhone> findByUserIdAndStatus(@Param("userId")int userId);

    void update(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    int insertSelective(Orders record);

     Orders findById2(int id);
}