package com.cnh.dao;

import com.cnh.dataobject.Phone;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
public interface PhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    int insert(Phone record);

    Phone findById(int id);

    int update(Phone phone);


    List<Phone> findAll (@Param("status") String status,@Param("phoneName")  String phoneName);

    void delete(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone
     *
     * @mbggenerated Tue Apr 14 23:40:33 CST 2020
     */
    int insertSelective(Phone record);
}